#!/bin/bash
# make_inventory.sh — READ-ONLY machine manifest generator (macOS / Linux / ARIS).
# Writes inventory/<machine-id>.md: git state + gitignored payloads + env.
# Sanitized: $HOME -> "~", $ARIS_WORK_ROOT -> literal '$ARIS_WORK_ROOT'.
# Usage (from anywhere inside the repo):
#     bash ops/make_inventory.sh <machine-id>     # e.g. macbook | aris
set -uo pipefail
MID="${1:?usage: bash ops/make_inventory.sh <machine-id>}"
ROOT="$(git rev-parse --show-toplevel)" || { echo "not a git repo" >&2; exit 1; }
REPO="$(basename "$ROOT")"
OUT_DIR="$ROOT/inventory"; mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/$MID.md"

san() { sed -e "s|${ARIS_WORK_ROOT:-__none__}|\$ARIS_WORK_ROOT|g" -e "s|$HOME|~|g"; }
mb()  { du -sm "$1" 2>/dev/null | cut -f1; }

{
echo "# Machine manifest — $MID"
echo
echo "*Generated by \`make_inventory.sh\` — READ-ONLY scan. Trust only as of the scan date.*"
echo
echo "| field | value |"
echo "|---|---|"
echo "| scanned | $(date '+%Y-%m-%d %H:%M') |"
echo "| repo | $REPO |"
echo "| os | $(uname -srm) |"
if command -v sw_vers >/dev/null 2>&1; then echo "| macos | $(sw_vers -productVersion) |"; fi
if command -v nvidia-smi >/dev/null 2>&1; then
  echo "| gpu | $(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader | paste -sd';' -) |"
else echo "| gpu | none detected (login node / no NVIDIA) |"; fi
echo "| disk free (repo fs) | $(df -h "$ROOT" | awk 'NR==2{print $4}') |"
echo "| repo path | $(echo "$ROOT" | san) |"
echo "| branch @ scan | $(git -C "$ROOT" branch --show-current) @ $(git -C "$ROOT" rev-parse --short HEAD) |"
echo "| dirty files @ scan | $(git -C "$ROOT" status --porcelain | wc -l | tr -d ' ') |"
echo
echo "## Gitignored payloads present on this machine"
echo
echo "What git cannot show other machines. Dir-level only."
echo
echo "| path (repo-relative) | size MB | files |"
echo "|---|---|---|"
cd "$ROOT"
git ls-files -o -i --directory --exclude-standard | while read -r e; do
  [ -e "$e" ] || continue
  if [ -d "$e" ]; then
    printf "| %s | %s | %s |\n" "${e%/}" "$(mb "$e")" "$(find "$e" -type f 2>/dev/null | wc -l | tr -d ' ')"
  else
    printf "| %s | %s | 1 |\n" "$e" "$(mb "$e")"
  fi
done | sort -t'|' -k3 -rn | head -50
echo
echo "## Python environments"
echo
for v in "$ROOT/.venv" "$(dirname "$ROOT")/.venv"; do
  [ -x "$v/bin/python" ] && echo "- $(echo "$v" | san): \`$("$v/bin/python" --version 2>&1)\`"
done
if command -v conda >/dev/null 2>&1; then
  # names only — never paths (a path here leaked a username once; see gitleaks hpc rules)
  echo "- conda envs: $(conda env list 2>/dev/null | awk 'NR>2 && $1 !~ /^[#\/]/ {print $1}' | paste -sd', ' - | san)"
fi
echo
echo "## HuggingFace cache (shared across repos on this machine)"
echo
HF="${HF_HOME:-$HOME/.cache/huggingface}/hub"
if [ -d "$HF" ]; then
  du -sm "$HF"/models--* 2>/dev/null | sort -rn | head -12 | while read -r s p; do
    echo "- $(basename "$p") — ${s} MB"
  done
else echo "- no HF cache found"; fi
echo
echo "## Config presence (never contents)"
echo
for c in aris.env .env; do
  if [ -f "$ROOT/$c" ]; then echo "- $c: yes"; else echo "- $c: no"; fi
done
[ -f "$HOME/aris.env" ] && echo "- ~/aris.env: yes"
} > "$OUT"
echo "manifest written: $(echo "$OUT" | san)"
