# make_inventory.ps1 - READ-ONLY machine manifest generator (Windows).
# Writes local/<MachineId>.md describing THIS machine's view of the repo:
# git state + gitignored payloads (the part other machines can't see) + env.
# Sanitized: home paths -> "~". Run from anywhere inside the repo:
#     powershell -ExecutionPolicy Bypass -File .\ops\make_inventory.ps1 [-MachineId laptop-4060]
param([string]$MachineId = "laptop-4060")

$ErrorActionPreference = "SilentlyContinue"
$root = git rev-parse --show-toplevel
if (-not $root) { Write-Error "not inside a git repo"; exit 1 }
$root = $root -replace '/', '\'
$repo = Split-Path $root -Leaf
$home_ = $env:USERPROFILE

function San([string]$s) {
    if ($null -eq $s) { return "" }
    return $s.Replace($home_, "~").Replace($home_.Replace('\','/'), "~")
}
function DirSizeMB([string]$p) {
    $b = (Get-ChildItem -LiteralPath $p -Recurse -Force -File | Measure-Object Length -Sum).Sum
    if ($null -eq $b) { $b = 0 }
    return [math]::Round($b / 1MB, 1)
}

$L = New-Object System.Collections.Generic.List[string]
$L.Add("# Machine manifest - $MachineId")
$L.Add("")
$L.Add("*Generated by ``make_inventory.ps1`` - READ-ONLY scan. Trust only as of the scan date.*")
$L.Add("")
$L.Add("| field | value |")
$L.Add("|---|---|")
$L.Add("| scanned | $(Get-Date -Format 'yyyy-MM-dd HH:mm') |")
$L.Add("| repo | $repo |")
$L.Add("| os | $([System.Environment]::OSVersion.VersionString) (Windows) |")
$cs = Get-CimInstance Win32_ComputerSystem
$L.Add("| ram | $([math]::Round($cs.TotalPhysicalMemory/1GB,0)) GB |")
$gpu = ""
try { $gpu = (nvidia-smi --query-gpu=name,memory.total --format=csv,noheader) -join '; ' } catch {}
if ($gpu) { $L.Add("| gpu | $gpu |") } else { $L.Add("| gpu | none detected |") }
$drive = (Get-PSDrive ($root.Substring(0,1))).Free
$L.Add("| disk free (repo drive) | $([math]::Round($drive/1GB,0)) GB |")
$L.Add("| repo path | $(San $root) |")
$L.Add("| branch @ scan | $(git -C $root branch --show-current) @ $(git -C $root rev-parse --short HEAD) |")
$dirty = (git -C $root status --porcelain | Measure-Object -Line).Lines
$L.Add("| dirty files @ scan | $dirty |")
$L.Add("")

$L.Add("## Gitignored payloads present on this machine")
$L.Add("")
$L.Add("What git cannot show other machines. Dir-level only.")
$L.Add("")
$L.Add("| path (repo-relative) | size MB | files |")
$L.Add("|---|---|---|")
Push-Location $root
$ignored = git ls-files -o -i --directory --exclude-standard
$rows = @()
foreach ($e in $ignored) {
    $p = Join-Path $root ($e -replace '/', '\')
    if (Test-Path -LiteralPath $p -PathType Container) {
        $mb = DirSizeMB $p
        $n = (Get-ChildItem -LiteralPath $p -Recurse -Force -File | Measure-Object).Count
    } elseif (Test-Path -LiteralPath $p) {
        $mb = [math]::Round((Get-Item -LiteralPath $p -Force).Length / 1MB, 1)
        $n = 1
    } else { continue }
    $rows += [pscustomobject]@{ Path = $e.TrimEnd('/'); MB = $mb; N = $n }
}
Pop-Location
$rows | Sort-Object MB -Descending | Select-Object -First 50 | ForEach-Object {
    $L.Add("| $($_.Path) | $($_.MB) | $($_.N) |")
}
if ($rows.Count -gt 50) { $L.Add("| ... ($($rows.Count - 50) more, smaller) | | |") }
$L.Add("")

$L.Add("## Python environments")
$L.Add("")
foreach ($v in @((Join-Path $root ".venv"), (Join-Path (Split-Path $root -Parent) ".venv"))) {
    $py = Join-Path $v "Scripts\python.exe"
    if (Test-Path $py) { $L.Add("- $(San $v): ``$((& $py --version))``") }
}
$L.Add("")

$L.Add("## HuggingFace cache (shared across repos on this machine)")
$L.Add("")
$hf = Join-Path $home_ ".cache\huggingface\hub"
if ($env:HF_HOME) { $hf = Join-Path $env:HF_HOME "hub" }
if (Test-Path $hf) {
    Get-ChildItem $hf -Directory | ForEach-Object {
        [pscustomobject]@{ Name = $_.Name; MB = (DirSizeMB $_.FullName) }
    } | Sort-Object MB -Descending | Select-Object -First 12 | ForEach-Object {
        $L.Add("- $($_.Name) - $($_.MB) MB")
    }
} else { $L.Add("- no HF cache found") }
$L.Add("")

$L.Add("## Config presence (never contents)")
$L.Add("")
foreach ($c in @(".env")) {
    $present = "no"
    if (Test-Path (Join-Path $root $c)) { $present = "yes" }
    $L.Add("- ${c}: $present")
}

$outDir = Join-Path $root "local"
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory $outDir | Out-Null }
$out = Join-Path $outDir "$MachineId.md"
$L | Set-Content -Path $out -Encoding utf8
Write-Host "manifest written: $(San $out)"
